config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@gmail.com\z/
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/controllers/admins/omniauth_callbacks_controller.rb
class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    admin = Admin.from_google(from_google_params)

    if admin.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect admin, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_admin_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_admin_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private

  def from_google_params
    @from_google_params ||= {
      uid: auth.uid,
      email: auth.info.email,
      full_name: auth.info.name,
      avatar_url: auth.info.image
    }
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  def after_sign_out_path_for(_resource_or_scope)
    new_admin_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include FeatureFlagHelper

  before_action :authenticate_admin!
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_current_admin

  def show
  end

  private

  def set_current_admin
    @current_admin = current_admin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feature_flag_helper.rb
module FeatureFlagHelper
  def beta_test?(current_user:)
    if current_user.email == ENV['BETA_TESTER_EMAIL'] && ENV['EXPERIMENT_ACTIVE'] == 'true' && ENV['RAILS_ENV'] != 'test'
      return true
    end

    false
  end
end

app/views/dashboards/show.html.erb
<div class='dashboard'>
  <div class='title'>
    <span class='title-image'><%= image_tag('broccoli-small.png') %></span>
    <h1 class='title-text'>Broccolizer |
    <%= link_to 'Salir', destroy_admin_session_path %></h1>
  </div>

  <nav class='sidenav'>
      <ul class='main-buttons'>
        <li>
          <%=
            if beta_test?(current_user: @current_admin)
              link_to 'Añadir alimento', '#', :method => :get , :class => 'nav-link'
            else
              link_to 'Próximamente', '#', :method => :get , :class => 'nav-link'
            end
          %>
        </li>
      </ul>
  </nav>

  <div class='charts'>
    <div class='chart'>
      En construcción
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Broccolizer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <body>
    <% if flash.any? %>
      <% flash.each do |key, value| -%>
        <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
      <% end -%>
    <% end %>
    <%= yield %>
  </body>
</html>